# Site Info
title: 'Devops of Googleok'
tagline: 'Devops of Googleok'
description: '구글러를 꿈꾸며 프로그래밍을 공부하며 배운점 느낀점을 기록하는 곳입니다.'
baseurl: ""
url: https://googleok.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: PARK JONGEOK
  description: 구글럭(PARK JONGEOK)
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/googleok
    facebook:  https://www.facebook.com/profile.php?id=100003521646301
    instagram: https://www.instagram.com/eok_1oooooooo/
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:    mailto:qkrwhddjr3@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { TIL (Today I Learned): '/#til' }
    - { 컴퓨터공학 : '/#컴퓨터공학' }
    - { spring: '/#spring' }
    - { java: '/#java' }
    - { Django: '/#django' }
    - { python: '/#python' }
    - { javascript: '/#javascript' }
    - { nodejs: '/#nodejs' }
    - { MySQL: '/#MySQL' }
    - { PostgreSQL: '/#PostgreSQL' }
    - { 알고리즘 문제풀이: '/#알고리즘-문제풀이' }
    - { git: '/#git' }
    - { Linux: '/#Linux' }
    - { etc: '/#etc' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-92094009-1' # leave blank if you don't want google analytics
disqus_short_name: 'wayhome25-github-io' # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate
